image: php:7.2

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - apt-get update -yqq
  - apt-get install -yqq zip
  - curl -sS https://getcomposer.org/installer | php

.build: &build
  stage: build
  artifacts: &artifacts
    name: $CI_PROJECT_NAME-${CI_COMMIT_TAG:-${CI_COMMIT_SHA:0:8}}
    paths:
      - src/
      - composer.json
      - composer.lock
      - wordpress-settings.php
    expire_in: 4 weeks
build:develop:
  <<: *build
  only:
    - develop
  script:
    - php composer.phar install --no-ansi
build:tag:
  <<: *build
  only:
    - /^feature.*$/
    - tags
  artifacts:
    <<: *artifacts
    expire_in: 10 yrs
  script:
    - php composer.phar install --no-ansi --no-dev
